### ISSUE TITLE
File udthesis.cls not found

### ISSUE THREAD

**Issue by rskonieczka** [dueyfinster/CSThesis#1]
` \usepackage
               [T1]{fontenc}^^M
*** (cannot \read from terminal in nonstop modes)
`

**Comment by dueyfinster** [comment]
It looks like LyX has not picked up the layout file, can you confirm you've selected it with Lyx?

You can put it in the templates directory (of your lyx config directory) or you can ask Lyx to use it by simply opening `thesis.lyx` and go in the menu to `Document` > `Settings` > Click "`Local Layout`" and choose the included file `udthesis.layout` (in the `templates` directory)

it has a line to tell Lyx that the class comes from sty:
` \DeclareLaTeXClass[report, udthesis.sty]{report (udthesis)}`

**Comment by dueyfinster** [comment]
I've also updated the repo so Lyx will now find the template, if you want to pull the latest and try that.
